spring:
  application:
    name: pos-server

  data:
    mongodb:
      port: 27017
      database: pos
      uri: mongodb://localhost

  mvc:
    problemdetails:
      enabled: true

server:
  port: 7085

